#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


SAFE_VIEW = "safe_view"
STATE_CHANGE = "state_change"
DESTRUCTIVE = "destructive"
EXTERNAL_EFFECT = "external_effect"
UNSUPPORTED_DYNAMIC = "unsupported_dynamic"


@dataclass(frozen=True)
class MenuAction:
    action_id: str
    menu_path: tuple[str, ...]
    shortcut: str | None = None
    safety: str = SAFE_VIEW
    implemented: bool = True
    preferred_tool: str | None = None
    note: str | None = None

    def as_dict(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            "action_id": self.action_id,
            "menu_path": list(self.menu_path),
            "label": self.menu_path[-1],
            "shortcut": self.shortcut,
            "safety": self.safety,
            "implemented": self.implemented,
            "requires_frontmost_xcode": True,
        }
        if self.preferred_tool:
            data["preferred_tool"] = self.preferred_tool
        if self.note:
            data["note"] = self.note
        return data


def action(
    action_id: str,
    *menu_path: str,
    shortcut: str | None = None,
    safety: str = SAFE_VIEW,
    implemented: bool = True,
    preferred_tool: str | None = None,
    note: str | None = None,
) -> MenuAction:
    return MenuAction(
        action_id=action_id,
        menu_path=menu_path,
        shortcut=shortcut,
        safety=safety,
        implemented=implemented,
        preferred_tool=preferred_tool,
        note=note,
    )


MENU_ACTIONS: tuple[MenuAction, ...] = (
    action("file.new", "File", "New", implemented=False, safety=EXTERNAL_EFFECT, note="Opens Xcode's New flow."),
    action("file.add_files", "File", "Add Files...", shortcut="⌥⌘A", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.add_package_dependencies", "File", "Add Package Dependencies...", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.open", "File", "Open...", shortcut="⌘O", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.open_recent", "File", "Open Recent", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("file.open_quickly", "File", "Open Quickly...", shortcut="⇧⌘O"),
    action("file.close_window", "File", "Close Window", shortcut="⌘W", safety=DESTRUCTIVE),
    action("file.close_new_editor", "File", "Close “New Editor”", shortcut="⌃⌘W", safety=DESTRUCTIVE),
    action("file.close_editor_pane", "File", "Close Editor Pane", shortcut="⌃⇧⌘W", safety=DESTRUCTIVE),
    action("file.close_project", "File", "Close Project", shortcut="⌃⌥⌘W", safety=DESTRUCTIVE),
    action("file.duplicate_editor_tab", "File", "Duplicate Editor Tab", safety=STATE_CHANGE),
    action("file.save", "File", "Save", shortcut="⌘S", safety=STATE_CHANGE),
    action("file.duplicate", "File", "Duplicate...", shortcut="⇧⌘S", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.revert_to_saved", "File", "Revert to Saved...", implemented=False, safety=DESTRUCTIVE),
    action("file.unlock", "File", "Unlock...", implemented=False, safety=STATE_CHANGE),
    action("file.export", "File", "Export...", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.show_in_finder", "File", "Show in Finder", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.open_in_new_tab", "File", "Open in New Tab", shortcut="⌥⌘O", safety=STATE_CHANGE),
    action("file.open_in_new_window", "File", "Open in New Window", safety=STATE_CHANGE),
    action("file.open_external_editor", "File", "Open with External Editor", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.packages", "File", "Packages", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("file.save_as_workspace", "File", "Save As Workspace...", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.project_settings", "File", "Project Settings...", safety=STATE_CHANGE),
    action("file.page_setup", "File", "Page Setup...", implemented=False, safety=EXTERNAL_EFFECT),
    action("file.print", "File", "Print...", shortcut="⌘P", implemented=False, safety=EXTERNAL_EFFECT),
    action("edit.undo", "Edit", "Undo", shortcut="⌘Z", safety=STATE_CHANGE),
    action("edit.redo", "Edit", "Redo", shortcut="⇧⌘Z", safety=STATE_CHANGE),
    action("edit.cut", "Edit", "Cut", shortcut="⌘X", safety=DESTRUCTIVE),
    action("edit.copy", "Edit", "Copy", "Copy", shortcut="⌘C"),
    action("edit.copy_file_and_line", "Edit", "Copy", "Copy File and Line", shortcut="⌃⌥⌘C"),
    action("edit.copy_symbol_name", "Edit", "Copy", "Copy Symbol Name", shortcut="⌃⇧⌘C"),
    action("edit.copy_qualified_symbol_name", "Edit", "Copy", "Copy Qualified Symbol Name", shortcut="⌃⌥⇧⌘C"),
    action("edit.paste", "Edit", "Paste", "Paste", shortcut="⌘V", safety=STATE_CHANGE),
    action("edit.paste_preserve_formatting", "Edit", "Paste", "Paste and Preserve Formatting", shortcut="⌥⇧⌘V", safety=STATE_CHANGE),
    action("edit.duplicate", "Edit", "Duplicate", shortcut="⌘D", safety=STATE_CHANGE),
    action("edit.delete", "Edit", "Delete", shortcut="⌘⌫", safety=DESTRUCTIVE),
    action("edit.select_all", "Edit", "Select All", shortcut="⌘A"),
    action("edit.add_line_bookmark", "Edit", "Add Line Bookmark", shortcut="⌃⌘'", safety=STATE_CHANGE),
    action("edit.add_file_bookmark", "Edit", "Add File Bookmark", shortcut="⌃⇧⌘'", safety=STATE_CHANGE),
    action("edit.sort", "Edit", "Sort", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("edit.format", "Edit", "Format", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("edit.convert", "Edit", "Convert", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("edit.autofill", "Edit", "AutoFill", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("edit.start_dictation", "Edit", "Start Dictation...", shortcut="🌐D", implemented=False, safety=EXTERNAL_EFFECT),
    action("edit.emoji_symbols", "Edit", "Emoji & Symbols", shortcut="🌐E", implemented=False, safety=EXTERNAL_EFFECT),
    action("view.editor.focus_editor_pane", "View", "Editor", "Focus Editor Pane", shortcut="⌃⇧⌘↩"),
    action("view.editor.show_related_items", "View", "Editor", "Show Related Items", shortcut="⌃1"),
    action("view.editor.show_previous_history", "View", "Editor", "Show Previous History", shortcut="⌃2"),
    action("view.editor.show_next_history", "View", "Editor", "Show Next History", shortcut="⌃3"),
    action("view.editor.show_top_level_items", "View", "Editor", "Show Top Level Items", shortcut="⌃4"),
    action("view.editor.show_group_files", "View", "Editor", "Show Group Files", shortcut="⌃5"),
    action("view.editor.show_document_items", "View", "Editor", "Show Document Items", shortcut="⌃6"),
    action("view.show_code_review", "View", "Show Code Review", shortcut="⌥⇧⌘↩"),
    action("view.show_editor_tab_bar", "View", "Show Editor Tab Bar"),
    action("view.pin_editor_tab", "View", "Pin Editor Tab", shortcut="⇧⌘P", safety=STATE_CHANGE),
    action("view.change_editor_orientation", "View", "Change Editor Orientation", safety=STATE_CHANGE),
    action("view.reset_editor_sizes", "View", "Reset Editor Sizes", safety=STATE_CHANGE),
    action("view.reset_assistant_selection", "View", "Reset Assistant Selection", shortcut="⌥⇧⌘Z", safety=STATE_CHANGE),
    action("view.show_quick_actions", "View", "Show Quick Actions...", shortcut="⇧⌘A"),
    action("view.navigator.project", "View", "Navigators", "Project", shortcut="⌘1"),
    action("view.navigator.source_control", "View", "Navigators", "Source Control", shortcut="⌘2"),
    action("view.navigator.bookmarks", "View", "Navigators", "Bookmarks", shortcut="⌘3"),
    action("view.navigator.find", "View", "Navigators", "Find", shortcut="⌘4"),
    action("view.navigator.issues", "View", "Navigators", "Issues", shortcut="⌘5"),
    action("view.navigator.tests", "View", "Navigators", "Tests", shortcut="⌘6"),
    action("view.navigator.debug", "View", "Navigators", "Debug", shortcut="⌘7"),
    action("view.navigator.breakpoints", "View", "Navigators", "Breakpoints", shortcut="⌘8"),
    action("view.navigator.reports", "View", "Navigators", "Reports", shortcut="⌘9"),
    action("view.navigator.coding_assistant", "View", "Navigators", "Show Coding Assistant", shortcut="⌘0"),
    action("view.navigator.hide", "View", "Navigators", "Hide Navigator"),
    action("view.navigator.filter", "View", "Navigators", "Filter in Navigator", shortcut="⌥⌘J"),
    action("view.debug_area.activate_console", "View", "Debug Area", "Activate Console", shortcut="⇧⌘C"),
    action("view.debug_area.hide", "View", "Debug Area", "Hide Debug Area", shortcut="⇧⌘Y"),
    action("view.inspector.file", "View", "Inspectors", "File", shortcut="⌥⌘1"),
    action("view.inspector.history", "View", "Inspectors", "History", shortcut="⌥⌘2"),
    action("view.inspector.quick_help", "View", "Inspectors", "Quick Help", shortcut="⌥⌘3"),
    action("view.inspector.hide", "View", "Inspectors", "Hide Inspector"),
    action("view.show_library", "View", "Show Library", shortcut="⇧⌘L"),
    action("view.reload_organizer", "View", "Reload Organizer", shortcut="⌃R", safety=STATE_CHANGE),
    action("view.hide_toolbar", "View", "Hide Toolbar", shortcut="⌥⌘T", safety=STATE_CHANGE),
    action("view.show_window_tab_bar", "View", "Show Window Tab Bar", safety=STATE_CHANGE),
    action("view.show_all_window_tabs", "View", "Show All Window Tabs", shortcut="⇧⌘\\", safety=STATE_CHANGE),
    action("view.customize_touch_bar", "View", "Customize Touch Bar...", implemented=False, safety=EXTERNAL_EFFECT),
    action("view.enter_full_screen", "View", "Enter Full Screen", shortcut="⌃⌘F", safety=STATE_CHANGE),
    action("find.find_in_project", "Find", "Find in Project...", shortcut="⇧⌘F"),
    action("find.find_replace_in_project", "Find", "Find and Replace in Project...", shortcut="⌥⇧⌘F"),
    action("find.next_in_project", "Find", "Find Next in Project", shortcut="⌃⌘G"),
    action("find.previous_in_project", "Find", "Find Previous in Project", shortcut="⌃⇧⌘G"),
    action("find.selected_text_in_project", "Find", "Find Selected Text in Project"),
    action("find.selected_words_in_project", "Find", "Find Selected Words in Project"),
    action("find.selected_symbol_in_project", "Find", "Find Selected Symbol in Project", shortcut="⌃⇧⌘F"),
    action("find.call_hierarchy", "Find", "Find Call Hierarchy", shortcut="⌃⇧⌘H"),
    action("find.ancestor_types", "Find", "Find Ancestor Types"),
    action("find.descendent_types", "Find", "Find Descendent Types"),
    action("find.conforming_types", "Find", "Find Conforming Types"),
    action("find.in_selected_groups", "Find", "Find in Selected Groups..."),
    action("find.find", "Find", "Find...", shortcut="⌘F"),
    action("find.find_replace", "Find", "Find and Replace...", shortcut="⌥⌘F"),
    action("find.next", "Find", "Find Next", shortcut="⌘G"),
    action("find.previous", "Find", "Find Previous", shortcut="⇧⌘G"),
    action("find.select_next", "Find", "Find and Select Next", shortcut="⌥⌘G"),
    action("find.select_previous", "Find", "Find and Select Previous", shortcut="⌥⇧⌘G"),
    action("find.replace", "Find", "Replace", safety=STATE_CHANGE),
    action("find.replace_all", "Find", "Replace All", safety=DESTRUCTIVE),
    action("find.replace_find_next", "Find", "Replace and Find Next", safety=STATE_CHANGE),
    action("find.replace_find_previous", "Find", "Replace and Find Previous", safety=STATE_CHANGE),
    action("find.use_selection_for_find", "Find", "Use Selection for Find", shortcut="⌘E"),
    action("find.use_selection_for_replace", "Find", "Use Selection for Replace", shortcut="⇧⌘E"),
    action("find.select_next_occurrence", "Find", "Select Next Occurrence", shortcut="⌥⌘E"),
    action("find.select_previous_occurrence", "Find", "Select Previous Occurrence", shortcut="⌥⇧⌘E"),
    action("find.select_all_matches", "Find", "Select All Find Matches"),
    action("find.select_matches_in_selection", "Find", "Select Find Matches in Selection"),
    action("find.hide_find_bar", "Find", "Hide Find Bar"),
    action("navigate.reveal_project", "Navigate", "Reveal in Project Navigator", shortcut="⇧⌘J"),
    action("navigate.reveal_changes", "Navigate", "Reveal in Changes Navigator", shortcut="⇧⌘M"),
    action("navigate.reveal_debug", "Navigate", "Reveal in Debug Navigator", shortcut="⇧⌘D"),
    action("navigate.open_using_tab", "Navigate", "Open using Tab", shortcut="⌥⌘,", safety=STATE_CHANGE),
    action("navigate.open_next_editor_pane", "Navigate", "Open in Next Editor Pane", shortcut="⌥⌘<", safety=STATE_CHANGE),
    action("navigate.focus_previous_area", "Navigate", "Move Focus to Previous Area", shortcut="⌥⇧⌘`"),
    action("navigate.focus_previous_editor_pane", "Navigate", "Move Focus to Previous Editor Pane", shortcut="⌃⇧`"),
    action("navigate.focus_editor_pane", "Navigate", "Move Focus to Editor Pane...", shortcut="⌘J"),
    action("navigate.previous_tab", "Navigate", "Show Previous Tab", shortcut="⌘{"),
    action("navigate.next_tab", "Navigate", "Show Next Tab", shortcut="⌘}"),
    action("navigate.next_history", "Navigate", "Show Next Location in History", shortcut="⌃⌘▶"),
    action("navigate.previous_history", "Navigate", "Show Previous Location in History", shortcut="⌃⌘◀"),
    action("navigate.jump_selection", "Navigate", "Jump to Selection", shortcut="⌥⌘L"),
    action("navigate.jump_definition", "Navigate", "Jump to Definition", shortcut="⌃⌘J"),
    action("navigate.jump_original_source", "Navigate", "Jump to Original Source/Generated Interface"),
    action("navigate.jump_last_destination", "Navigate", "Jump to Last Destination"),
    action("navigate.next_issue", "Navigate", "Jump to Next Issue", shortcut="⌘'"),
    action("navigate.previous_issue", "Navigate", "Jump to Previous Issue", shortcut='⌘"'),
    action("navigate.next_bookmark", "Navigate", "Jump to Next Bookmark", shortcut="⌃;"),
    action("navigate.previous_bookmark", "Navigate", "Jump to Previous Bookmark", shortcut="⌃:"),
    action("navigate.instruction_pointer", "Navigate", "Jump to Instruction Pointer", shortcut="⌃⌘P"),
    action("editor.show_editor_only", "Editor", "Show Editor Only", shortcut="⌘↩"),
    action("editor.preview", "Editor", "Preview", shortcut="⌥⌘↩"),
    action("editor.assistant", "Editor", "Assistant", shortcut="⌃⌥⌘↩"),
    action("editor.layout.automatic", "Editor", "Layout", "Automatic"),
    action("editor.layout.left", "Editor", "Layout", "Editor on Left"),
    action("editor.layout.top", "Editor", "Layout", "Editor on Top"),
    action("product.run", "Product", "Run", shortcut="⌘R", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_run"),
    action("product.test", "Product", "Test", shortcut="⌘U", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_test"),
    action("product.profile", "Product", "Profile", shortcut="⌘I", implemented=False, safety=STATE_CHANGE, note="Profiling is a long-running IDE workflow and is not menu-clicked in this pass."),
    action("product.analyze", "Product", "Analyze", shortcut="⇧⌘B", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.archive", "Product", "Archive", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.build_for.running", "Product", "Build For", "Running", shortcut="⇧⌘R", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.build_for.testing", "Product", "Build For", "Testing", shortcut="⇧⌘U", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.build_for.profiling", "Product", "Build For", "Profiling", shortcut="⇧⌘I", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.perform.run_without_building", "Product", "Perform Action", "Run Without Building", shortcut="⌃⌘R", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_run"),
    action("product.perform.test_without_building", "Product", "Perform Action", "Test Without Building", shortcut="⌃⌘U", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_test"),
    action("product.perform.profile_without_building", "Product", "Perform Action", "Profile Without Building", shortcut="⌃⌘I", implemented=False, safety=STATE_CHANGE, note="Profiling is a long-running IDE workflow and is not menu-clicked in this pass."),
    action("product.perform.build_timing_summary", "Product", "Perform Action", "Build with Timing Summary", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.perform.build_export_test_products", "Product", "Perform Action", "Build and Export Test Products", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.perform.test", "Product", "Perform Action", "Test", shortcut="⌃⌥⌘U", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_test"),
    action("product.perform.test_again", "Product", "Perform Action", "Test Again", shortcut="⌃⌥⌘G", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_test"),
    action("product.perform.compile_file", "Product", "Perform Action", "Compile File", shortcut="⌃⌘B", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.perform.analyze_file", "Product", "Perform Action", "Analyze File", shortcut="⌃⇧⌘B", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.build", "Product", "Build", shortcut="⌘B", implemented=False, safety=STATE_CHANGE, preferred_tool="xcode_ide_build"),
    action("product.clean_build_folder", "Product", "Clean Build Folder...", shortcut="⇧⌘K", safety=DESTRUCTIVE),
    action("product.clear_test_results", "Product", "Clear Test Results", shortcut="⌃⌥⌘K", safety=DESTRUCTIVE),
    action("product.clear_all_issues", "Product", "Clear All Issues", safety=DESTRUCTIVE),
    action("product.stop", "Product", "Stop", shortcut="⌘.", implemented=False, safety=DESTRUCTIVE, preferred_tool="xcode_ide_run"),
    action("product.build_documentation", "Product", "Build Documentation", shortcut="⌃⇧⌘D", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.show_build_folder", "Product", "Show Build Folder in Finder", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.copy_build_folder_path", "Product", "Copy Build Folder Path"),
    action("product.export_localizations", "Product", "Export Localizations...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.import_localizations", "Product", "Import Localizations...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.scheme.choose", "Product", "Scheme", "Choose Scheme", shortcut="⌃0", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_schemes"),
    action("product.scheme.next", "Product", "Scheme", "Select Next Scheme", shortcut="⌃⌘]", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_schemes"),
    action("product.scheme.previous", "Product", "Scheme", "Select Previous Scheme", shortcut="⌃⌘[", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_schemes"),
    action("product.scheme.edit", "Product", "Scheme", "Edit Scheme...", shortcut="⌘<", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.scheme.new", "Product", "Scheme", "New Scheme...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.scheme.manage", "Product", "Scheme", "Manage Schemes...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.scheme.convert_test_plans", "Product", "Scheme", "Convert Scheme to use Test Plans...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.scheme.dynamic", "Product", "Scheme", "<project schemes>", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_schemes"),
    action("product.destination.choose", "Product", "Destination", "Choose Destination", shortcut="⌃⇧0", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_destinations"),
    action("product.destination.next", "Product", "Destination", "Select Next Destination", shortcut="⌃⌥⌘]", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_destinations"),
    action("product.destination.previous", "Product", "Destination", "Select Previous Destination", shortcut="⌃⌥⌘[", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_destinations"),
    action("product.destination.show_all", "Product", "Destination", "Show All Run Destinations", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_destinations"),
    action("product.destination.manage", "Product", "Destination", "Manage Run Destinations...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.destination.dynamic", "Product", "Destination", "<run destinations>", implemented=False, safety=UNSUPPORTED_DYNAMIC, preferred_tool="xcode_ide_list_destinations"),
    action("product.test_plan.next", "Product", "Test Plan", "Select Next Test Plan", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("product.test_plan.previous", "Product", "Test Plan", "Select Previous Test Plan", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("product.test_plan.edit", "Product", "Test Plan", "Edit Test Plan", shortcut="⌘>", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.test_plan.new", "Product", "Test Plan", "New Test Plan...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.test_plan.manage", "Product", "Test Plan", "Manage Test Plans...", implemented=False, safety=EXTERNAL_EFFECT),
    action("product.test_plan.dynamic", "Product", "Test Plan", "<test plans>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("product.app_shortcuts_preview", "Product", "App Shortcuts Preview", implemented=False, safety=EXTERNAL_EFFECT),
    action("debug.pause", "Debug", "Pause", shortcut="⌃⌘Y", safety=STATE_CHANGE),
    action("debug.continue_current_line", "Debug", "Continue To Current Line", shortcut="⌃⌘C", safety=STATE_CHANGE),
    action("debug.step_over", "Debug", "Step Over", shortcut="F6", safety=STATE_CHANGE),
    action("debug.step_into", "Debug", "Step Into", shortcut="F7", safety=STATE_CHANGE),
    action("debug.step_out", "Debug", "Step Out", shortcut="F8", safety=STATE_CHANGE),
    action("debug.step_over_instruction", "Debug", "Step Over Instruction", shortcut="⌃F6", safety=STATE_CHANGE),
    action("debug.step_over_thread", "Debug", "Step Over Thread", shortcut="⌃⇧F6", safety=STATE_CHANGE),
    action("debug.step_into_instruction", "Debug", "Step Into Instruction", shortcut="⌃F7", safety=STATE_CHANGE),
    action("debug.step_into_thread", "Debug", "Step Into Thread", shortcut="⌃⇧F7", safety=STATE_CHANGE),
    action("debug.deactivate_breakpoints", "Debug", "Deactivate Breakpoints", shortcut="⌘Y", safety=STATE_CHANGE),
    action("debug.breakpoint.current_line", "Debug", "Breakpoints", "Create Breakpoint at Current Line", shortcut="⌘\\", safety=STATE_CHANGE),
    action("debug.breakpoint.enable_disable_current_line", "Debug", "Breakpoints", "Enable/Disable Breakpoint at Current Line", safety=STATE_CHANGE),
    action("debug.breakpoint.selection", "Debug", "Breakpoints", "Create Breakpoint for Selection", safety=STATE_CHANGE),
    action("debug.breakpoint.delete_column_current_line", "Debug", "Breakpoints", "Delete Column Breakpoints at Current Line", safety=DESTRUCTIVE),
    action("debug.breakpoint.swift_error", "Debug", "Breakpoints", "Create Swift Error Breakpoint", safety=STATE_CHANGE),
    action("debug.breakpoint.exception", "Debug", "Breakpoints", "Create Exception Breakpoint...", safety=STATE_CHANGE),
    action("debug.breakpoint.symbolic", "Debug", "Breakpoints", "Create Symbolic Breakpoint...", shortcut="⌥⌘\\", safety=STATE_CHANGE),
    action("debug.breakpoint.test_failure", "Debug", "Breakpoints", "Create Test Failure Breakpoint", safety=STATE_CHANGE),
    action("debug.breakpoint.delete_all", "Debug", "Breakpoints", "Delete All Breakpoints", safety=DESTRUCTIVE),
    action("debug.console.copy_visible_metadata", "Debug", "Console", "Copy Row with Visible Metadata", shortcut="⌥⇧C"),
    action("debug.console.copy_all_metadata", "Debug", "Console", "Copy Row with All Metadata"),
    action("debug.console.copy_without_metadata", "Debug", "Console", "Copy Row without Metadata"),
    action("debug.console.jump_source", "Debug", "Console", "Jump To Source", shortcut="⌥⇧⌘J"),
    action("debug.console.hide_similar.dynamic", "Debug", "Console", "Hide Similar Items", "<metadata fields>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.console.show_similar.dynamic", "Debug", "Console", "Show Similar Items", "<metadata fields>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.console.clear", "Debug", "Console", "Clear Console", shortcut="⌘K", safety=DESTRUCTIVE),
    action("debug.console.reload", "Debug", "Console", "Reload Console", shortcut="⌥⌘K", safety=STATE_CHANGE),
    action("debug.console.select_last_output", "Debug", "Console", "Select Last Output", shortcut="⌥⇧⌘A"),
    action("debug.workflow.view_memory", "Debug", "Debug Workflow", "View Memory", shortcut="⌃⌥⇧⌘M"),
    action("debug.workflow.interrupt", "Debug", "Debug Workflow", "Interrupt Debugger Operation", shortcut="⌃C", safety=STATE_CHANGE),
    action("debug.attach_pid_or_name", "Debug", "Attach to Process by PID or Name...", implemented=False, safety=EXTERNAL_EFFECT),
    action("debug.attach_process", "Debug", "Attach to Process", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.detach.dynamic", "Debug", "Detach from <running app>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.debug_executable", "Debug", "Debug Executable...", implemented=False, safety=EXTERNAL_EFFECT),
    action("debug.simulate_location.dynamic", "Debug", "Simulate Location", "<locations>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.simulate_background_fetch", "Debug", "Simulate Background Fetch", safety=STATE_CHANGE),
    action("debug.simulate_metrickit_payloads", "Debug", "Simulate MetricKit Payloads", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.simulate_ui_snapshot", "Debug", "Simulate UI Snapshot", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.view_debugging.screenshot", "Debug", "View Debugging", "Take Screenshot of Active Device", implemented=False, safety=EXTERNAL_EFFECT),
    action("debug.view_debugging.capture_hierarchy", "Debug", "View Debugging", "Capture View Hierarchy", safety=STATE_CHANGE),
    action("debug.view_debugging.show_frames", "Debug", "View Debugging", "Show View Frames", safety=STATE_CHANGE),
    action("debug.view_debugging.show_alignment", "Debug", "View Debugging", "Show Alignment Rectangles", safety=STATE_CHANGE),
    action("debug.view_debugging.show_drawing", "Debug", "View Debugging", "Show View Drawing", safety=STATE_CHANGE),
    action("debug.view_debugging.show_responsive_scrolling", "Debug", "View Debugging", "Show Responsive Scrolling Status", safety=STATE_CHANGE),
    action("debug.view_debugging.configure_overrides", "Debug", "View Debugging", "Configure Environment Overrides...", implemented=False, safety=EXTERNAL_EFFECT),
    action("debug.view_debugging.disable_overrides", "Debug", "View Debugging", "Disable All Environment Overrides", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.dynamic", "Debug", "View Debugging", "Rendering", "<rendering options>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.view_debugging.rendering.color_blended_layers", "Debug", "View Debugging", "Rendering", "Color Blended Layers", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.color_hits_green_misses_red", "Debug", "View Debugging", "Rendering", "Color Hits Green and Misses Red", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.color_copied_images", "Debug", "View Debugging", "Rendering", "Color Copied Images", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.color_layer_formats", "Debug", "View Debugging", "Rendering", "Color Layer Formats", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.color_immediately", "Debug", "View Debugging", "Rendering", "Color Immediately", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.color_misaligned_images", "Debug", "View Debugging", "Rendering", "Color Misaligned Images", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.color_offscreen_rendered_yellow", "Debug", "View Debugging", "Rendering", "Color Offscreen-Rendered Yellow", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.color_compositing_fast_path_blue", "Debug", "View Debugging", "Rendering", "Color Compositing Fast-Path Blue", safety=STATE_CHANGE),
    action("debug.view_debugging.rendering.flash_updated_regions", "Debug", "View Debugging", "Rendering", "Flash Updated Regions", safety=STATE_CHANGE),
    action("debug.view_debugging.appearance.dynamic", "Debug", "View Debugging", "Appearance", "<appearance options>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("debug.view_debugging.appearance.system", "Debug", "View Debugging", "Appearance", "System Appearance", safety=STATE_CHANGE),
    action("debug.view_debugging.appearance.light", "Debug", "View Debugging", "Appearance", "Light", safety=STATE_CHANGE),
    action("debug.view_debugging.appearance.dark", "Debug", "View Debugging", "Appearance", "Dark", safety=STATE_CHANGE),
    action("debug.view_debugging.appearance.high_contrast_light", "Debug", "View Debugging", "Appearance", "High Contrast Light", safety=STATE_CHANGE),
    action("debug.view_debugging.appearance.high_contrast_dark", "Debug", "View Debugging", "Appearance", "High Contrast Dark", safety=STATE_CHANGE),
    action("debug.storekit.dynamic", "Debug", "StoreKit", "<transactions>", implemented=False, safety=EXTERNAL_EFFECT),
    action("debug.gamekit.dynamic", "Debug", "GameKit", "<gamekit actions>", implemented=False, safety=EXTERNAL_EFFECT),
    action("window.minimize", "Window", "Minimize", shortcut="⌘M", safety=STATE_CHANGE),
    action("window.zoom", "Window", "Zoom", safety=STATE_CHANGE),
    action("window.fill", "Window", "Fill", shortcut="⌃🌐F", safety=STATE_CHANGE),
    action("window.center", "Window", "Center", shortcut="⌃🌐C", safety=STATE_CHANGE),
    action("window.move_resize.left", "Window", "Move & Resize", "Left", shortcut="⌃🌐←", safety=STATE_CHANGE),
    action("window.move_resize.right", "Window", "Move & Resize", "Right", shortcut="⌃🌐→", safety=STATE_CHANGE),
    action("window.move_resize.top", "Window", "Move & Resize", "Top", shortcut="⌃🌐↑", safety=STATE_CHANGE),
    action("window.move_resize.bottom", "Window", "Move & Resize", "Bottom", shortcut="⌃🌐↓", safety=STATE_CHANGE),
    action("window.move_resize.top_left", "Window", "Move & Resize", "Top Left", safety=STATE_CHANGE),
    action("window.move_resize.top_right", "Window", "Move & Resize", "Top Right", safety=STATE_CHANGE),
    action("window.move_resize.bottom_left", "Window", "Move & Resize", "Bottom Left", safety=STATE_CHANGE),
    action("window.move_resize.bottom_right", "Window", "Move & Resize", "Bottom Right", safety=STATE_CHANGE),
    action("window.move_resize.left_and_right", "Window", "Move & Resize", "Left & Right", shortcut="⌃⇧🌐←", safety=STATE_CHANGE),
    action("window.move_resize.right_and_left", "Window", "Move & Resize", "Right & Left", shortcut="⌃⇧🌐→", safety=STATE_CHANGE),
    action("window.move_resize.top_and_bottom", "Window", "Move & Resize", "Top & Bottom", shortcut="⌃⇧🌐↑", safety=STATE_CHANGE),
    action("window.move_resize.bottom_and_top", "Window", "Move & Resize", "Bottom & Top", shortcut="⌃⇧🌐↓", safety=STATE_CHANGE),
    action("window.move_resize.quarters", "Window", "Move & Resize", "Quarters", safety=STATE_CHANGE),
    action("window.move_resize.return_previous_size", "Window", "Move & Resize", "Return to Previous Size", shortcut="⌃🌐R", safety=STATE_CHANGE),
    action("window.full_screen_tile.left", "Window", "Full Screen Tile", "Left of Screen", safety=STATE_CHANGE),
    action("window.full_screen_tile.right", "Window", "Full Screen Tile", "Right of Screen", safety=STATE_CHANGE),
    action("window.move_retina_display", "Window", "Move to Built-in Retina Display", safety=STATE_CHANGE),
    action("window.rename_tab", "Window", "Rename Window Tab...", shortcut="⌥⇧⌘T", safety=STATE_CHANGE),
    action("window.previous_tab", "Window", "Show Previous Window Tab", shortcut="⌃⇧→"),
    action("window.next_tab", "Window", "Show Next Window Tab", shortcut="⌃→"),
    action("window.move_tab_new_window", "Window", "Move Tab to New Window", safety=STATE_CHANGE),
    action("window.merge_all", "Window", "Merge All Windows", safety=STATE_CHANGE),
    action("window.developer_documentation", "Window", "Developer Documentation", shortcut="⇧⌘0", implemented=False, safety=EXTERNAL_EFFECT),
    action("window.welcome", "Window", "Welcome to Xcode", shortcut="⇧⌘1", implemented=False, safety=EXTERNAL_EFFECT),
    action("window.devices_simulators", "Window", "Devices and Simulators", shortcut="⇧⌘2", implemented=False, safety=EXTERNAL_EFFECT),
    action("window.downloads", "Window", "Downloads", shortcut="⇧⌘9", implemented=False, safety=EXTERNAL_EFFECT),
    action("window.organizer", "Window", "Organizer", shortcut="⌥⇧⌘O", implemented=False, safety=EXTERNAL_EFFECT),
    action("window.touch_bar.show", "Window", "Touch Bar", "Show Touch Bar", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("window.touch_bar.first_generation", "Window", "Touch Bar", "Touch Bar (1st generation)", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("window.touch_bar.second_generation", "Window", "Touch Bar", "Touch Bar (2nd generation)", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("window.touch_bar.dynamic", "Window", "Touch Bar", "<touch bar actions>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
    action("window.bring_all_front", "Window", "Bring All to Front", safety=STATE_CHANGE),
    action("window.dynamic_open_windows", "Window", "<open windows>", implemented=False, safety=UNSUPPORTED_DYNAMIC),
)


MENU_ACTIONS_BY_ID: dict[str, MenuAction] = {item.action_id: item for item in MENU_ACTIONS}
